version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: track
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9390310322
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/track
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 9390310322
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    restart: always

volumes:
  pgdata: 